package:
    name: pyscan
    version: 2.0.0

build:
  number: 1

source:
    path: ..

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - pyepics
        - bsread

    test:
         - pcaspy

test:
  source_files:
    - tests/

about:
    summary: "PyScan is a python class that performs a scan for single or multiple given knobs."
