package:
    name: pyscan
    version: 2.7.0

build:
  number: 0

source:
    path: ..

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - pyepics
        - bsread
        - requests

test:
  source_files:
    - tests/

about:
    summary: "PyScan is a python class that performs a scan for single or multiple given knobs."
